### ISSUE TITLE
Can't build, missing go.mod

### ISSUE THREAD

**Issue by brontide** [bemasher/rtltcp#3]
I'm good with plenty of languages but this new version of go is throwing me through a loop.  I can't build rtltcp.go directly and it automatically creates all the directories without write protection so I can't even add go.mod.  rtlamr builds but without rtltcp it's not very useful.  Any pointers would be appreciated.

**Comment by bemasher** [comment]
This is a direct dependency of rtlamr, if this package can't be built, rtlamr's build will fail. Do you mean the `rtl_tcp` tool provided by osmosdr? You will need to download or build that separately.

https://osmocom.org/projects/rtl-sdr/wiki/Rtl-sdr#Binary-Builds

**Comment by brontide** [comment]
Sorry about that confusion I was thinking the go module provided the binaries.
